### PR TITLE
Timestamps

### PR DESCRIPTION
**Pull request by mikeroll**
Before:
`alert.StartsAt` was used for any event. `resolved` and repeated alerts still had the timestamp of their first firing.  

After:
If an alert is `firing`, use `alert.StartsAt` as sentry event timestamp, for `resolved` use `alert.EndsAt`.

However with this approach, repeated notifications of the same alerts (within `repeat_interval`) will still have the timestamp of `alert.StartsAt` - this may or may not be desirable. Introducing `--dumb-timestamps` to be able to choose a simple `time.Now` instead of the above logic.

### CODE REVIEW

**Comment by mikeroll** [comment]
Could you please build a `v0.3.0` after merging this one? Thank you!

**Comment by summerwind** [comment]
0f6cde9 is duplicated commit with #4. Can you clean up your commit please?

> Could you please build a v0.3.0 after merging this one? Thank you!

Of course! I'm going to release v0.3.0 after merging.

Would you like to continue developing this gateway? I can transfer this repository to you if you are OK.

**Comment by mikeroll** [comment]
Yeah sorry, clumsy rebase.

Well I don't intend to do super active development, just a hack here and there to support the workflow I need (and I guess these are enough). If you do not want the project anymore, sure, I can adopt it.

**Review by summerwind — APPROVED** [review]

**Comment by summerwind** [comment]
Thanks for the quick response. LGTM 👍 

I believe that this gateway is still very useful but I'm giving up to maintain for now. So after releasing v0.3.0, I will transfer this repo to you. Thank you for your acceptance!

**Comment by summerwind** [comment]
Just released v0.3.0: https://github.com/summerwind/alertmanager-sentry-gateway/releases/tag/v0.3.0

**Comment by summerwind** [comment]
@mikeroll Oops, I couldn't transfer the repository due to you have a forked  repository. Please let me know when you delete your forked repository.

**Comment by mikeroll** [comment]
Deleted my fork. Thank you for your time and for the original work!

**Comment by summerwind** [comment]
I just sent transfer request. Thank you!

**Pull request merged**
