### PR TITLE
Tags and Fingerprint

### PR DESCRIPTION
**Pull request by mikeroll**
**Tags**: Alert.Labels serve the same purpose as Sentry's tags - let's use them directly.
**Fingerprint**: Allow to control sentry event grouping via a config option.

### CODE REVIEW

**Comment by summerwind** [comment]
Thank you for your PR! I think that this changes are very useful. 
Can you resolve conflicts please?

**Comment by mikeroll** [comment]
Resolved.
Would it be possible for you to build a `v0.3.0` after merging this?
Thank you!

**Comment by mikeroll** [comment]
Resolved, plus I pulled the new logic into functions to make it a bit cleaner.

**Review by summerwind — APPROVED** [review]

**Comment by summerwind** [comment]
Thank you for your effort!

**Pull request merged**
